reveal-md:
	# reveal-md --theme sky --title "Python tutorial for Deep Learning @ BIG (EPFL)" slides_reveal.md
	reveal-md --theme league --title "Python tutorial for Deep Learning @ BIG (EPFL)" slides_reveal.md
